"""4. rename calender_year to fiscal_year for income statement

Revision ID: 2561e31dd52e
Revises: c8b344f3c73b
Create Date: 2025-07-09 21:26:12.144795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2561e31dd52e'
down_revision = 'c8b344f3c73b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income_statements', sa.Column('fiscal_year', sa.String(length=4), nullable=False))
    op.drop_column('income_statements', 'calendar_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income_statements', sa.Column('calendar_year', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.drop_column('income_statements', 'fiscal_year')
    # ### end Alembic commands ###