"""Create detailed financial statement tables

Revision ID: 7ad54668721a
Revises: a3919207c4d6
Create Date: 2025-07-08 21:02:53.884687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ad54668721a'
down_revision = 'a3919207c4d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_sheet_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('calendar_year', sa.String(length=4), nullable=False),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('total_stockholders_equity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', 'period', name='_symbol_date_period_uc_balance')
    )
    op.create_index('idx_balance_sheet_statements_symbol_date', 'balance_sheet_statements', ['symbol', 'date'], unique=False)
    op.create_index(op.f('ix_balance_sheet_statements_date'), 'balance_sheet_statements', ['date'], unique=False)
    op.create_index(op.f('ix_balance_sheet_statements_id'), 'balance_sheet_statements', ['id'], unique=False)
    op.create_index(op.f('ix_balance_sheet_statements_symbol'), 'balance_sheet_statements', ['symbol'], unique=False)
    op.create_table('cash_flow_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('calendar_year', sa.String(length=4), nullable=False),
    sa.Column('net_cash_provided_by_operating_activities', sa.Float(), nullable=True),
    sa.Column('net_cash_used_for_investing_activities', sa.Float(), nullable=True),
    sa.Column('net_cash_used_by_financing_activities', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', 'period', name='_symbol_date_period_uc_cash')
    )
    op.create_index('idx_cash_flow_statements_symbol_date', 'cash_flow_statements', ['symbol', 'date'], unique=False)
    op.create_index(op.f('ix_cash_flow_statements_date'), 'cash_flow_statements', ['date'], unique=False)
    op.create_index(op.f('ix_cash_flow_statements_id'), 'cash_flow_statements', ['id'], unique=False)
    op.create_index(op.f('ix_cash_flow_statements_symbol'), 'cash_flow_statements', ['symbol'], unique=False)
    op.create_table('income_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('calendar_year', sa.String(length=4), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('cost_of_revenue', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('epsdiluted', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', 'period', name='_symbol_date_period_uc')
    )
    op.create_index('idx_income_statements_symbol_date', 'income_statements', ['symbol', 'date'], unique=False)
    op.create_index(op.f('ix_income_statements_date'), 'income_statements', ['date'], unique=False)
    op.create_index(op.f('ix_income_statements_id'), 'income_statements', ['id'], unique=False)
    op.create_index(op.f('ix_income_statements_symbol'), 'income_statements', ['symbol'], unique=False)
    op.drop_index(op.f('idx_financial_statements_symbol_date'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_calendar_year'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_date'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_id'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_symbol'), table_name='financial_statements')
    op.drop_table('financial_statements')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_statements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('calendar_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cost_of_revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gross_profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gross_profit_margin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('operating_expenses', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('operating_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('operating_margin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('net_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('net_margin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('eps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('revenue_growth_yoy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('revenue_growth_qoq', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('filing_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('accepted_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('financial_statements_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('financial_statements_pkey'))
    )
    op.create_index(op.f('ix_financial_statements_symbol'), 'financial_statements', ['symbol'], unique=False)
    op.create_index(op.f('ix_financial_statements_id'), 'financial_statements', ['id'], unique=False)
    op.create_index(op.f('ix_financial_statements_date'), 'financial_statements', ['date'], unique=False)
    op.create_index(op.f('ix_financial_statements_calendar_year'), 'financial_statements', ['calendar_year'], unique=False)
    op.create_index(op.f('idx_financial_statements_symbol_date'), 'financial_statements', ['symbol', 'date'], unique=False)
    op.drop_index(op.f('ix_income_statements_symbol'), table_name='income_statements')
    op.drop_index(op.f('ix_income_statements_id'), table_name='income_statements')
    op.drop_index(op.f('ix_income_statements_date'), table_name='income_statements')
    op.drop_index('idx_income_statements_symbol_date', table_name='income_statements')
    op.drop_table('income_statements')
    op.drop_index(op.f('ix_cash_flow_statements_symbol'), table_name='cash_flow_statements')
    op.drop_index(op.f('ix_cash_flow_statements_id'), table_name='cash_flow_statements')
    op.drop_index(op.f('ix_cash_flow_statements_date'), table_name='cash_flow_statements')
    op.drop_index('idx_cash_flow_statements_symbol_date', table_name='cash_flow_statements')
    op.drop_table('cash_flow_statements')
    op.drop_index(op.f('ix_balance_sheet_statements_symbol'), table_name='balance_sheet_statements')
    op.drop_index(op.f('ix_balance_sheet_statements_id'), table_name='balance_sheet_statements')
    op.drop_index(op.f('ix_balance_sheet_statements_date'), table_name='balance_sheet_statements')
    op.drop_index('idx_balance_sheet_statements_symbol_date', table_name='balance_sheet_statements')
    op.drop_table('balance_sheet_statements')
    # ### end Alembic commands ###
