"""Initial migration

Revision ID: a3919207c4d6
Revises: 
Create Date: 2025-07-01 22:32:57.969867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3919207c4d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=True)
    op.create_table('model_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('target_metric', sa.String(length=50), nullable=False),
    sa.Column('evaluation_date', sa.DateTime(), nullable=False),
    sa.Column('evaluation_period_start', sa.DateTime(), nullable=False),
    sa.Column('evaluation_period_end', sa.DateTime(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('r2_score', sa.Float(), nullable=True),
    sa.Column('predictions_count', sa.Integer(), nullable=True),
    sa.Column('rank_by_rmse', sa.Integer(), nullable=True),
    sa.Column('rank_by_mape', sa.Integer(), nullable=True),
    sa.Column('is_best_model', sa.Boolean(), nullable=True),
    sa.Column('companies_evaluated', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_performance_evaluation_date'), 'model_performance', ['evaluation_date'], unique=False)
    op.create_index(op.f('ix_model_performance_id'), 'model_performance', ['id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('mentioned_symbols', sa.String(length=200), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_news_published_sentiment', 'news_articles', ['published_date', 'sentiment_score'], unique=False)
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_published_date'), 'news_articles', ['published_date'], unique=False)
    op.create_table('financial_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('calendar_year', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('cost_of_revenue', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('gross_profit_margin', sa.Float(), nullable=True),
    sa.Column('operating_expenses', sa.Float(), nullable=True),
    sa.Column('operating_income', sa.Float(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('net_margin', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('revenue_growth_yoy', sa.Float(), nullable=True),
    sa.Column('revenue_growth_qoq', sa.Float(), nullable=True),
    sa.Column('filing_date', sa.DateTime(), nullable=True),
    sa.Column('accepted_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_financial_statements_symbol_date', 'financial_statements', ['symbol', 'date'], unique=False)
    op.create_index(op.f('ix_financial_statements_calendar_year'), 'financial_statements', ['calendar_year'], unique=False)
    op.create_index(op.f('ix_financial_statements_date'), 'financial_statements', ['date'], unique=False)
    op.create_index(op.f('ix_financial_statements_id'), 'financial_statements', ['id'], unique=False)
    op.create_index(op.f('ix_financial_statements_symbol'), 'financial_statements', ['symbol'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('target_metric', sa.String(length=50), nullable=False),
    sa.Column('prediction_date', sa.DateTime(), nullable=False),
    sa.Column('prediction_period', sa.String(length=10), nullable=False),
    sa.Column('prediction_year', sa.Integer(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('confidence_interval_lower', sa.Float(), nullable=True),
    sa.Column('confidence_interval_upper', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('training_rmse', sa.Float(), nullable=True),
    sa.Column('training_mape', sa.Float(), nullable=True),
    sa.Column('training_r2', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('prediction_error', sa.Float(), nullable=True),
    sa.Column('absolute_percentage_error', sa.Float(), nullable=True),
    sa.Column('training_data_points', sa.Integer(), nullable=True),
    sa.Column('features_used', sa.Text(), nullable=True),
    sa.Column('model_parameters', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_predictions_symbol_date', 'ml_predictions', ['symbol', 'prediction_date'], unique=False)
    op.create_index(op.f('ix_ml_predictions_id'), 'ml_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_prediction_date'), 'ml_predictions', ['prediction_date'], unique=False)
    op.create_index(op.f('ix_ml_predictions_symbol'), 'ml_predictions', ['symbol'], unique=False)
    op.create_table('revenue_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('calendar_year', sa.Integer(), nullable=False),
    sa.Column('segment_name', sa.String(length=255), nullable=False),
    sa.Column('segment_type', sa.String(length=50), nullable=True),
    sa.Column('segment_revenue', sa.Float(), nullable=True),
    sa.Column('segment_percentage', sa.Float(), nullable=True),
    sa.Column('segment_growth_yoy', sa.Float(), nullable=True),
    sa.Column('segment_growth_qoq', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_revenue_segments_symbol_date', 'revenue_segments', ['symbol', 'date'], unique=False)
    op.create_index(op.f('ix_revenue_segments_date'), 'revenue_segments', ['date'], unique=False)
    op.create_index(op.f('ix_revenue_segments_id'), 'revenue_segments', ['id'], unique=False)
    op.create_index(op.f('ix_revenue_segments_symbol'), 'revenue_segments', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revenue_segments_symbol'), table_name='revenue_segments')
    op.drop_index(op.f('ix_revenue_segments_id'), table_name='revenue_segments')
    op.drop_index(op.f('ix_revenue_segments_date'), table_name='revenue_segments')
    op.drop_index('idx_revenue_segments_symbol_date', table_name='revenue_segments')
    op.drop_table('revenue_segments')
    op.drop_index(op.f('ix_ml_predictions_symbol'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_prediction_date'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_id'), table_name='ml_predictions')
    op.drop_index('idx_predictions_symbol_date', table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_financial_statements_symbol'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_id'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_date'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_calendar_year'), table_name='financial_statements')
    op.drop_index('idx_financial_statements_symbol_date', table_name='financial_statements')
    op.drop_table('financial_statements')
    op.drop_index(op.f('ix_news_articles_published_date'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_index('idx_news_published_sentiment', table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_model_performance_id'), table_name='model_performance')
    op.drop_index(op.f('ix_model_performance_evaluation_date'), table_name='model_performance')
    op.drop_table('model_performance')
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
