"""3rd migration

Revision ID: c8b344f3c73b
Revises: 7ad54668721a
Create Date: 2025-07-08 23:09:26.270932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b344f3c73b'
down_revision = '7ad54668721a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###