"""7. resolving segment name

Revision ID: e2261d374520
Revises: ea5ceade0156
Create Date: 2025-07-10 03:11:07.979168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2261d374520'
down_revision = 'ea5ceade0156'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_revenue_segment', 'revenue_segments', ['symbol', 'date', 'segment_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_revenue_segment', 'revenue_segments', type_='unique')
    # ### end Alembic commands ###