"""migrating new api endpoints

Revision ID: e6c3594a6884
Revises: 77e4d1cf7a32
Create Date: 2025-07-27 20:07:58.645662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c3594a6884'
down_revision = '77e4d1cf7a32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_ratios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('net_profit_margin', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('gross_profit_margin', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('return_on_equity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('price_to_earnings_ratio', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('price_to_book_ratio', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('price_to_sales_ratio', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ev_to_ebitda', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('debt_to_equity_ratio', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('quick_ratio', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('asset_turnover', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('inventory_turnover', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=4), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('reported_currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', 'period', name='_symbol_date_period_uc_ratios')
    )
    op.create_index(op.f('ix_financial_ratios_company_id'), 'financial_ratios', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_ratios_date'), 'financial_ratios', ['date'], unique=False)
    op.create_index(op.f('ix_financial_ratios_id'), 'financial_ratios', ['id'], unique=False)
    op.create_index(op.f('ix_financial_ratios_symbol'), 'financial_ratios', ['symbol'], unique=False)
    op.create_table('key_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('enterprise_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('free_cash_flow_yield', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('return_on_equity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=4), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('reported_currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', 'period', name='_symbol_date_period_uc_metrics')
    )
    op.create_index(op.f('ix_key_metrics_company_id'), 'key_metrics', ['company_id'], unique=False)
    op.create_index(op.f('ix_key_metrics_date'), 'key_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_key_metrics_id'), 'key_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_key_metrics_symbol'), 'key_metrics', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_key_metrics_symbol'), table_name='key_metrics')
    op.drop_index(op.f('ix_key_metrics_id'), table_name='key_metrics')
    op.drop_index(op.f('ix_key_metrics_date'), table_name='key_metrics')
    op.drop_index(op.f('ix_key_metrics_company_id'), table_name='key_metrics')
    op.drop_table('key_metrics')
    op.drop_index(op.f('ix_financial_ratios_symbol'), table_name='financial_ratios')
    op.drop_index(op.f('ix_financial_ratios_id'), table_name='financial_ratios')
    op.drop_index(op.f('ix_financial_ratios_date'), table_name='financial_ratios')
    op.drop_index(op.f('ix_financial_ratios_company_id'), table_name='financial_ratios')
    op.drop_table('financial_ratios')
    # ### end Alembic commands ###