"""6. remaining name fix

Revision ID: ea5ceade0156
Revises: 99c95777d060
Create Date: 2025-07-10 02:59:53.557938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5ceade0156'
down_revision = '99c95777d060'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###